### ISSUE TITLE
Go lint CI keeps failing

### ISSUE THREAD

**Issue by atnomoverflow** [null-channel/eddington#17]
The go CI keep failing and not without even checking linting.

**Comment by Klaven** [comment]
The fix is not hard. just needs done. i'll jump on this this week. Always start with the inters so you don't run into this issue :)

**Comment by Klaven** [comment]
initial fix https://github.com/null-channel/eddington/pull/23 fixed all lint errors though I think something else is wrong with the github action.

**Comment by atnomoverflow** [comment]
@Klaven i think its fair to close this issue and open new one if needed then
